version: '3'
services:
    api:
        build: ./backend
        ports:
            - "5000:5000"
        volumes:
            - ./backend:/web
        environment:
            - PORT:5000

    frontend:
        container_name: frontend
        build: ./frontend
        ports:
            - "3000:3000"
        environment:
            - PORT:3000